Main page
sqdfy/sqdfy-web pull request #1
Opened 2024-02-02 19:05 UTC by yuli-ageeva

2024-02-03 08:41 UTC, vadimkor56 requested changes
В целом все хорошо, оставил несколько комментов. Визуально чуть позже смогу посмотреть

2024-02-04 10:28 UTC, vadimkor56 commented on src/pages/MainPage.jsx
> +        setIsSuccess(true)
Эндпоинта еще нет для сохранения email'а?

2024-02-04 10:47 UTC, yuli-ageeva commented on src/pages/MainPage.jsx
> +        setIsSuccess(true)
пока нет, Олег работает над этим

2024-02-04 10:48 UTC, vadimkor56 requested changes
**По визуальной части:**

1. Давай поменяем focus state для инпута на тот, что в дизайне:
<img width="524" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/038b0afd-3af6-41f8-aa05-1a9382ec65ae">

<img width="375" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/52901b78-3593-434a-bc90-a9906289673a">

2. Давай добавим отступ для формы справа, чтобы она не прилипала к краю экрана
<img width="1440" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/f0175a79-395a-4852-86fc-3d1a3291f0d5">

3. Вот в такой раскладке форму нужно равнять с текстом
Было:
<img width="967" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/d4a3aa60-a916-42cf-9f46-8ac18e649912">
Стало:
<img width="966" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/37b5363a-c89b-4929-953d-5d6458eaef2f">

4. На телефонах появляется скролл — и вертикальный, и горизонтальный
<img width="568" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/a955cc38-3979-4fc3-83f1-99a4b9c9076f">

5. На телефонах немного едет вертска:
<img width="555" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/e899ee60-8d56-47e8-b6f8-2f27ce00af06">

2024-02-04 10:51 UTC, vadimkor56 commented
На узких экранах, текст почему-то переносится в местах, где не должен
<img width="355" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/cdf1f124-fe79-4259-bce2-a6992e6797c7">

2024-02-05 13:37 UTC, vadimkor56 commented on public/index.html
>          <title>Squadify</title>
Давай все-таки поменяем title :)

2024-02-05 13:39 UTC, vadimkor56 commented on src/pages/MainPage.jsx
> +    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
Это лучше вынести из компонента наверх, сейчас это пересоздается на каждый рендер

2024-02-05 13:45 UTC, vadimkor56 commented on src/pages/MainPage.jsx
> +    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
Давай использовать что-то типа этого: 

> /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/

или это:

> /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/

https://emailregex.com/index.html

2024-02-05 13:56 UTC, vadimkor56 commented
Вертикальный скролл появился, давай уберем. Если экран очень маленький, то окей, но на стандартных лучше убрать
<img width="1440" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/491786d9-2fb6-4bae-bde7-8d3ee3c4e4f6">

2024-02-05 14:00 UTC, vadimkor56 commented
По поводу формы:
1. Отступ сверху больше чем сбоку
2. По-хорошему, ошибку валидации нужно убирать, если юзер вернулся в инпут (onFocus)

Вообще я сейчас так думаю — возможно нам вообще не стоит дизейблить кнопку, можно просто триггерить ошибку валидации при клике, если она есть. При этом не нужно показывать ошибку, когда пользователь начал исправлять свой email
<img width="529" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/ebe83cc1-6853-4b66-975d-2361955e09ea">

2024-02-05 20:22 UTC, vadimkor56 commented
Кстати, давай еще на введенный текст накинем те же стили, что и у placeholder'а, чтобы консистентно было:
<img width="549" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/5f908484-9739-4b37-b93a-667a9e3114f9">
<img width="553" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/18e6e62e-45a9-4ee7-b6d8-871ec4b5860c">

Вот пример из [дизайна](https://www.figma.com/file/AXJVNSmhqKhh947PQsuV2C/sqdfy?type=design&node-id=842-2870&mode=design&t=MNyCQIlhOyeXEVGZ-0):
<img width="720" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/f8285fd7-713b-4781-85dc-0ead211b9f00">

2024-02-05 21:35 UTC, vadimkor56 commented on public/index.html
> +        <title>Sqdfy</title>
Спасибо!
Давай только с маленькой писать — sqdfy

2024-02-05 21:41 UTC, vadimkor56 commented on public/index.html
> +        <link rel="icon" href="../src/images/sqdfy.svg" />
Фавиконка сейчас не загружается
<img width="90" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/0ba87d9d-6e52-4250-9b7b-ed352b2e32b6">
<img width="877" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/d2d036d9-3d79-47dd-81a2-6e51437cf4cf">

Относительный путь тут не будет работать, к сожалению, потому что в сбилженной версии нет папки src. Нужно добавить ассет в ./public и использовать `href="./sqdfy.svg"`:
<img width="82" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/13ba1bc9-b388-4bfd-a998-38e5151b27f9">

2024-02-05 22:03 UTC, vadimkor56 commented
Пара моментов по визуальной части:
1. Давай выровняем отступы сверху и снизу
<img width="480" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/fce7efd1-73a9-43d9-8cc2-51145519aa46">

2. Давай внешний радиус сделаем 56px
<img width="501" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/778fdc55-d78c-44e0-b00e-06f64e3112df">

3. Давай попробуем вертикально выровнить вот этот блок с текстом относительно середины квадратного блока с формой:
<img width="1050" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/26414076-66c1-4e95-b929-45be53a6b1ed">

4. Давай отцентруем контент, чтобы отступы слева и справа были одинаковыми:
<img width="1440" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/baa11e01-1bb3-41df-8615-d4d989dcf443">

2024-02-07 20:36 UTC, vadimkor56 commented
Давай еще текст обновим внизу. Поняли, что нужно рассказать про возможность отписаться от рассылки
<img width="468" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/2b305101-8987-4976-8574-2e73fbbe8d19">

2024-02-08 20:54 UTC, vadimkor56 commented
1. Между 912px и 970px почему-то пропадает часть формы снизу
<img width="828" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/4058d5d9-c927-4071-b052-a97b2c2c10d9">

2. Кажется, у формы бордер сверху меньше чем сбоку на средних экранах
<img width="370" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/a8ffecd4-4a03-40ba-9c61-abe73920448c">

Сверху 11px, по бокам 15px. Но сверху почему-то небольшой зазор между бордером и контентом
<img width="628" alt="image" src="https://github.com/sqdfy/sqdfy-web/assets/34280044/04fb6dcc-bb4c-423e-b0d1-3f282b5bd6f7">

2024-02-08 21:01 UTC, vadimkor56 approved these changes
Выглядит очень круто! 🔥 Спасибо
Оставил пару минорных комментов, но можем в следующей итерации пофиксить

2024-02-08 21:04 UTC, merged